dash/urls.py
from django.urls import path
from .views import *
app_name='dash'
urlpatterns=[
    path('index/', index, name='index'),
]

gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('user/', include('user.urls')),
    path('dashboard/', include('dash.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from.views import *
app_name='photo'
urlpatterns=[
    path('', index, name='index'),
    path('detail/<int:id>/', view_photo, name='detail'),
    path('create/',create_photo, name='create'),
    path('update/edit/<int:id>/', update_photo, name='edit'),
    path('delete/<int:id>/', delete_photo, name='delete'),
    path('category/search/', search_pic, name='search'),
]

user/urls.py
from django.urls import path
from .views import *
app_name='user'
urlpatterns=[
    path('login/', sign_in, name='login'),
    path('register/', sign_up, name='register'),
    path('logout/', sign_out, name='logout')

]

dash/models.py
from django.db import models

# Create your models here.

photo/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name=models.CharField(max_length=120)

    class Meta:
        ordering=['-name']
        verbose_name_plural='Categories'

    def __str__(self):
        return self.name    
    

class Pic(models.Model):
    category=models.ForeignKey(Category, related_name='pics', on_delete=models.SET_NULL, null=True)
    name=models.CharField(max_length=50)
    description=models.TextField(blank=True, null=True)
    image=models.ImageField(upload_to='image')
    created_by=models.ForeignKey(User,related_name='pics',on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering=['-name']
    
    def __str__(self):
        return  self.name

photo/forms.py
from django.forms import ModelForm
from .models import Pic
from django import forms

INPUT_CLASSES='w-full py-4 px-6 rounded-xl border'
class PicForm(forms.ModelForm):
     class Meta:
        model=Pic
        fields=['category','name','description','image',]
        widgets={
             'category':forms.Select(attrs={
              'class':INPUT_CLASSES
       }),
       'name':forms.TextInput(attrs={
              'class':INPUT_CLASSES
       }),
       'description':forms.Textarea(attrs={
              'class':INPUT_CLASSES
       }),
       'image':forms.FileInput(attrs={
              'class':INPUT_CLASSES
       }),
        }

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

INPUT_CLASSES='w-full px-6 py-4 rounded-xl'
class LoginForm(forms.Form):
    username=forms.CharField(max_length=60, widget=forms.TextInput(attrs={
        'placeholder':'Enter your username ',
        'class':'w-full px-6 py-4 rounded-xl',
    }))
    password=forms.CharField(max_length=60, widget=forms.PasswordInput(attrs={
        'placeholder':'Enter your password',
        'class':'w-full py-4 px-6 rounded-xl '
    }))

class RegisterForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']

    username=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username',
        'class':'w-full py-4 px-6 rounded-xl'
    }))   
    email=forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Your email address',
        'class':'w-full py-4 px-6 rounded-xl'
    })) 
    password1=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password',
        'class':'w-full py-4 px-6 rounded-xl'
    })) 
    password2=forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Repeat your password',
        'class':'w-full py-4 px-6 rounded-xl'
    })) 

dash/views.py
from django.shortcuts import render
from photo.models import *
def index(request):
    categories=Category.objects.all()
    pics=Pic.objects.filter(created_by=request.user)
    return render(request, 'dash/index.html',{'pics':pics,'categories':categories})

photo/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.db.models import Q
from .models import *
from django.contrib.auth.decorators import login_required
from .forms import *

def index(request):
    categories=Category.objects.all()
    pics=Pic.objects.all()
    context={'categories':categories,'pics':pics}
    return render(request, 'photo/index.html', context )

def view_photo(request, id):
    pics=get_object_or_404(Pic,id=id)
    related_items=Pic.objects.filter(category=pics.category).exclude(id=id)[0:3]
    context={'pics':pics,
             'related_items':related_items}
    return render(request, 'photo/view.html', context)

@login_required
def create_photo(request):
    if request.method == 'GET':
        context={'form':PicForm()}
        return render(request,'photo/create.html',context)
    
    elif request.method =='POST':
        form=PicForm(request.POST,request.FILES)
        if form.is_valid():
            user=form.save(commit=False)
            user.created_by=request.user
            user.save()
            return redirect('photo:detail', id=user.id)
        else:
            return render(request,'photo/create.html', {'form':form})
        
@login_required
def update_photo(request,id):
    query=Pic.objects.filter(created_by=request.user)
    pic=get_object_or_404(query, id=id)
    if request.method == 'GET':
        context={'form':PicForm(instance=pic),'id':id}
        return render(request,'photo/create.html',context)  

    elif request.method =='POST':
        form=PicForm(request.POST, instance=pic)
        if form.is_valid():
            form.save()
            return redirect('photo:index')
        else:
            return render(request, 'photo/create.html', {'form':form})         
        




@login_required
def delete_photo(request, id):
    query=Pic.objects.filter(created_by=request.user)
    pic=get_object_or_404(query, id=id) 
    context={'pic':pic}
    if request.method =='GET':
        return render(request,'photo/delete_pic.html', context)

    elif request.method =="POST":
        pic.delete()
        return redirect('photo:index')       
    



  
def  search_pic(request):
    query=request.GET.get('query','')
    category_id=request.GET.get('category',0)
    categories=Category.objects.all()
    pics=Pic.objects.all()
    if category_id:
        pics=pics.filter(category_id=category_id)
    if query:
        pics=pics.filter(Q(name__icontains=query)|Q(description__icontains=query)) 
    return render(request,'photo/pics.html',{
        'query':query,
        'category_id':int(category_id),
        'pics':pics,
        'categories':categories,
    })        

user/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import *
from django.contrib.auth import login, logout, authenticate
def sign_in(request):
    if request.method =='GET':
        if request.user.is_authenticated:
            return redirect('photo:index')
        
        form=LoginForm()
        context={'form':form}
        return render(request, 'user/login.html',context)
    elif request.method =="POST":
        form=LoginForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user=authenticate(request,username=username,password=password)
            if user:
                login(request,user)
                messages.success(request,f'You have logged in succesfully {request.user.username} !!')
                return redirect('photo:index')
            
        messages.error(request,f'Please correct the following error')
        return render(request,'user/login.html', {'form':form})
def sign_up(request):
    if request.method =='GET':
        form=RegisterForm()
        context={'form':form}
        return render(request, 'user/sign_up.html', context)
    
    elif request.method =='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.username=user.username.lower()
            user.save()
            messages.success(request,'You have signed up successfully')
            login(request,user)
            return redirect('photo:index')
        else:
            return render(request, 'user/sign_up.html',{'form':form})
    

def sign_out(request):
    logout(request)
    messages.success(request, 'You\'ve Logged out successfully')
    return redirect('photo:index')
    # return redirect('user:login')
    

dash/templates/dash/index.html
{% extends 'photo/base.html' %}

{% block  content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="text-2xl text-center font-semibold">My Pics</h2>
     
      <div class="grid grid-cols-3 gap-2 sm:grid-cols-3">
        {% for pic in pics %}
        <div class="px-6 py-12">
          <a href="{% url 'photo:detail' pic.id %}" class="">
            {% if pics %}
            <img src="{{ pic.image.url }}" class="object-cover  sm:w-96 w-96 h-64 rounded-t-xl" alt="{{ image.pic.name }}">
            {% endif %}
            <div class="px-6 py-12 bg-white rounded-b-xl ">
              <h5 class="text-lg "><strong>{{pic.name}}</strong></h5>
              <p class="mb-6 text-gray-500">{{ pic.description }}</p>
              <a href="{% url 'photo:detail' pic.id %}" class=" px-4 py-2 bg-teal-500 flex justify-center items-center font-semibold text-white rounded-xl hover:bg-teal-700">View Photo</a>
            </div>
          </a>
        </div>
            {% endfor %}
          </div>
      </div>
<div class=" mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class=" text-2xl font-semibold text-center">Categories</h2>
    <div class="mt-2 grid grid-cols-3 gap-3">
      {% for category in categories %}
       <a href="{% url 'photo:search' %}?query={{query}}&category={{category.id}}" class="">
        <div class="p-6 bg-white rounded-b-xl">
          <h4 class="text-lg font-semibold">{{category.name}}</h4>
          <p class="text-lg ">{{category.pics.count}} pics</p>
         </div>
       </a>
     
       {% endfor %}
    </div>
  </div>
{% endblock %}

photo/templates/photo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} Photo</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200 bg-gray-100">
            <a class="text-xl font-semibold" href="{% url 'photo:index' %}">Gallery</a>
          <div class="space-x-6" >
                    <a class="text-lg font-semibold hover:text-gray-500" href="{% url 'photo:create' %}">Create</a>
                    <a class="text-lg font-semibold hover:text-gray-500" href="{% url 'photo:search' %}">Browse</a>
              {% if request.user.is_authenticated %}
                <a class="px-4 py-2 text-lg  font-semibold bg-gray-500 rounded-xl hover:bg-gray-700 text-white" href="{% url 'user:logout' %}">Logout</a>
             <a class="px-4 py-2 text-lg font-semibold bg-teal-500 rounded-xl hover:bg-teal-700 text-white" href="{% url 'dash:index' %}">Dashboard</a>
              {% else %}
                <a class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700" href="{% url 'user:login' %}">Login</a>
                <a class=" px-6 py-3 text-lg font-semibold bg-gray-500 rounded-xl hover:bg-gray-700 text-white" href="{% url 'user:register' %}">Sign Up</a>
              {% endif %}
          </div>
        
      </nav>
      <div class="px-6 py-6">
      
            {% block content %}

            {% endblock %}
      </div>
      <footer class="px-6 py-6 bg-gray-800 flex justify-between">
        <div class="w-2/3 pr-10">
          <h3 class="text-lg text-gray-500 font-semibold mb-6">About</h3>
          <p class="text-lg text-gray-400">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto deleniti in doloremque? Sed aspernatur cumque accusantium praesentium ipsa. Itaque, quaerat. Aliquam totam molestiae sequi facilis vero cupiditate laboriosam magnam ratione!
          </p>
        </div>
        <div class="w-1/3">
          <h3 class="text-gray-500 mb-5">Menu</h3>
          <ul class="space-y-2">
            <li><a href="" class="text-lg text-teal-500 hover:text-teal-700">About </a></li>
            <li><a href="" class="text-teal-500 text-lg hover:text-teal-700">Contact</a></li>
            <li><a href="" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
            <li><a href="" class="text-lg text-teal-500 hover:text-teal-700">Terms of service</a></li>
          </ul>
        </div>

      </footer>
</body>
</html>

photo/templates/photo/create.html
{% extends 'photo/base.html' %}


{% block content %}
<h2 class="text-2xl font-semibold text-center ">{% if id %}Edit {% else%} New{% endif %} Post</h2>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Create" class="w-1/3 mt-4 px-6 py-3 text-white font-semibold  rounded-xl bg-teal-500 hover:bg-teal-700">
</form>
{% endblock %}

photo/templates/photo/delete_pic.html
{% extends 'photo/base.html' %}

{% block title %}
{% endblock %}

{% block content  %}
<form action="" method="post">
{% csrf_token %}
<p>Are you sure you want to delete <strong>{{pic.name}}</strong>?</p>
<input type="submit" value="Confirm">
<a href="{% url 'photo:index' %}" class="">Cancel</a>
</form>

{% endblock %}

photo/templates/photo/index.html
{% extends 'photo/base.html' %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
<h2 class="text-2xl text-center font-semibold">Latest Pic</h2>
 
  <div class="grid grid-cols-3 gap-2 sm:grid-cols-3">
    {% for pic in pics %}
    <div class="px-6 py-12">
      <a href="{% url 'photo:detail' pic.id %}" class="">
        {% if pics %}
        <img src="{{ pic.image.url }}" class="object-cover  sm:w-96 w-96 h-64 rounded-t-xl" alt="{{ image.pic.name }}">
        {% endif %}
        <div class="px-6 py-12 bg-white rounded-b-xl ">
          <h5 class="text-lg "><strong>{{pic.name}}</strong></h5>
          <p class="mb-6 text-gray-500">{{ pic.description }}</p>
          <a href="{% url 'photo:detail' pic.id %}" class=" px-4 py-2 bg-teal-500 flex justify-center items-center font-semibold text-white rounded-xl hover:bg-teal-700">View Photo</a>
        </div>
      </a>
    </div>
        {% endfor %}
      </div>
  </div>
<div class=" mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class=" text-2xl font-semibold text-center">Categories</h2>
  <div class="mt-2 grid grid-cols-3 gap-3">
    {% for category in categories %}
     <a href="{% url 'photo:search' %}?query={{query}}&category={{category.id}}" class="">
      <div class="p-6 bg-white rounded-b-xl">
        <h4 class="text-lg font-semibold">{{category.name}}</h4>
        <p class="text-lg ">{{category.pics.count}} pics</p>
       </div>
     </a>
   
     {% endfor %}
  </div>
</div>

{% endblock %}

photo/templates/photo/pics.html
{% extends 'photo/base.html' %}

{% block content %}
<div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
   <div class="col-span-1">
    <form action="" method="get">
      <input type="text" name="query" value="{{query}}" placeholder="Search here...." class="w-full px-4 py-2 border rounded-xl">
        <input type="submit" value="search" class=" mt-2 pt-4  px-4 py-2 text-lg text-white bg-teal-500 rounded-xl hover:bg-teal-700">
  </form>
  <hr class="my-4">
  <p class="font-semibold text-lg text-center">Categories</p>
  <ul>

  {% for category in categories %}
  <li class="px-2 py-2 rounded-xl text-center {% if category.id == category_id %} bg-gray-400 font-semibold{% endif %}">
    <a href="{% url 'photo:search' %}?query={{query}}&category={{category.id}}" class="">{{category.name}}</a></li>
  {% endfor %}
  <hr class="my-4">
  <p class="font-semibold text-lg text-center">Clear </p>
  <a href="{% url 'photo:search' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear filter </a>
  </ul>
</div>
<div class="col-span-3">
  <div class="grid grid-cols-3 gap-3">
    {% for pic in pics %}
   <a href="{% url 'photo:detail' pic.id %}" class="">
    <div>
      <img src="{{pic.image.url}}" alt="{{pic.pic.name}}" class="rounded-t-xl">
     </div>
  
        <div class="bg-white rounded-b-xl">
      <h2 class="text-2xl">{{pic.name}}</h2>
      <p class="text-lg ">{{pic.description}}</p>
      </div>
   </a>
    {% endfor %}
  </div>

</div>



</div>

{% endblock %}

photo/templates/photo/view.html
{% extends 'photo/base.html' %}

{% block title %}

{{ pics.name}} |
{% endblock %}

{% block content %}
<div class="grid grid-cols-3 gap-6">
     
     <div class="col-span-2">
          {% if pics %}
          <img src="{{pics.image.url}}" alt="{{pic.pic.name}}" class="object-cover  sm:w-96 w-96 h-64 rounded-xl ">
          {% endif %}
     <div class="w-3/4 col-span-3 p-6 bg-gray-100 rounded-xl ">
          <h4 class="mb-6 text-3xl font-semibold ">{{pics.name}}</h4>
          <p class="text-gray-700">{{pics.description}}</p><br>
        {% if request.user.is_authenticated and request.user == pics.created_by %}
        <div class="mt-6 p-6 bg-white rounded-xl">
          <a href="{% url 'photo:edit' pics.id %}" class="px-6 py-3 text-white text-lg font-semibold rounded-xl bg-teal-500 hover:bg-teal-700">Update</a>
          <a href="{% url 'photo:delete' pics.id %}" class="px-6 py-3  text-white text-lg font-semibold rounded-xl bg-red-500 hover:bg-red-700">Delete</a>
          {% endif %}
          <a href="{% url 'photo:index' %}" class="px-6 py-3 rounded-xl text-lg text-white font-semibold bg-gray-500 hover:bg-gray-800">Go back</a>
                      </div>
</div>
</div>
</div>

    
       <div class="mt-6 px-6 py-12 rounded-xl bg-gray-100">
               <h2 class="text-2xl text-center font-semibold mb-6">Related Pics</h2>
               <div class="grid grid-cols-3 gap-4">
               {% for pic in related_items %}
              
                    {% if pic.image %}
                    <a href="{% url 'photo:detail' pic.id %}" class="">
                    <img src="{{ pic.image.url }}" alt="{{pic.pic.name}}" class="object-cover  sm:w-96 w-96 h-64 rounded-t-xl">
                    <div class="px-6 py-12 bg-white rounded-b-xl">  </div>
                         <h4 class="text-xl font-semibold px-4 py-2 ">{{pic.name}}</h4>
                    <p class="text-lg  px-4 py-2">{{pic.description}}</p>
                  
                    </a>
                   
                         {% endif %}
               
             
               {% endfor %}
          </div>

       </div>

{% endblock %}

user/templates/user/login.html
{% extends 'photo/base.html' %}



{% block content %}
<div class="w-1/2 mx-auto bg-gray-100 rounded-xl px-6 py-12">


    <h2 class="text-2xl font-semibold text-gray-800 text-center">Login</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Login" class="mt-5 px-4 py-2 w-full text-lg font-semibold bg-teal-500 rounded-xl hover:bg-teal-800">
    </form>
    <p class="mt-3 py-2 px-2 mx-auto">Don't have an account ?<a href="{% url 'user:register' %}" class="text-lg text-teal-500 hover:text-teal-700">SignUp</a></p>
  


</div>
{% endblock %}

user/templates/user/sign_up.html
{% extends 'photo/base.html'%}

{% block content %}
<div class="w-1/2 mx-auto bg-gray-100 rounded-xl px-6 py-12">
    <h2 class="mb-4 text-2xl font-semibold text-gray-800 text-center">Sign Up</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{form.non_field_errors }}
        <div class="mb-3">
            <label for="" class="inline-block">Username</label><br>
            {{form.username}}
        </div>
        <div class="mb-3">
            <label for="" class="inline-block">Email</label><br>
            {{form.email}}
        </div>
        <div class="mb-3">
            <label for="" class="inline-block">password</label><br>
            {{form.password1}}
        </div>
        <div class="mb-3">
            <label for="" class="inline-block">Repeat password</label><br>
            {{form.password2}}
        </div>
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{field.errors}}
               {% endfor %}
               {{ form.non_filed_errors }}
        </div>
        {% endif %}
        <input type="submit" value="Sign Up" class="mt-5 w-full px-4 py-2 rounded-xl  text-lg font-semibold bg-teal-500 hover:bg-teal-800">
    </form>
    <p class="mt-3 py-2 px-2 mx-auto">Already have an account ?<a href="{% url 'user:login' %}" class="text-lg text-teal-500 hover:text-teal-700">Login</a></p>
</div>

{% endblock %}